
/* Retrieves a value in a position in a matrix */

GetValue(Matrix, Type, Count):=block([Positions,Band,Stack,Row,Column,CMRow,CMColumn],
    load(GetPositions),    if Type=SudokuMatrix then (        Positions:GetPositions(Count,(length(Matrix[1]))^2),        Band:Positions[1],        Stack:Positions[2],        Row:Positions[3],        Column:Positions[4],        Value:Matrix[Band,Stack][Row,Column]    ),    if Type=CombMatrix then (        Positions:GetPositions(Count,length(Matrix[1])),        CMRow:Positions[5],        CMColumn:Positions[6],        Value:Matrix[CMRow,CMColumn]    ),    Value);

