
/* Removes random values until no more can be removed whilst preserving a unique solution  */RemoveAllRandomGivens(CombMatrix):=block([N:length(CombMatrix[1]),ListOfRemCells,CNFSolM],    load(LoadRemoving),
    LoadRemoving(),
    SeedRandom(),    ListOfRemCells:GenListRemCells(CombMatrix),    CNFSolM:ConvertToCNF(CombMatrix,true),

    for i:1 thru 1 do(
        RemoveOneRandomGiven(CombMatrix,CNFSolM,ListOfRemCells)
    )
);

